spring:
  servlet:
    session:
      timeout: 3600
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: hsrOptimiser

logging:
  level:
    root: INFO
    com.hsrOptimiser.engine: TRACE

asagi:
  url: "https://honkai.asagi-game.com"

simulated-annealing:
  initial-temperature: 10
  cooling-rate: 0.9
  epoch: 100